<? /* @var $this \Zend\View\Renderer\PhpRenderer */ ?>
<!DOCTYPE html>
<html lang="ru-ru" dir="ltr">
<head>
    <?= $this->headTitle()->setSeparator(' - ') ?>
    <meta charset="UTF-8">
    <meta name="description" content="<?=$this->headTitle()?>">
    <meta http-equiv="Content-Language" content="ru">
    <?= $this->headMeta() ?>


    <? $this->headLink()->prependStylesheet($this->basePath('css/style.css')); ?>
    <? $this->headLink()->prependStylesheet($this->basePath('css/catalog.css')); ?>
    <? $this->headLink()->prependStylesheet($this->basePath('css/bootstrap.min.css')); ?>
    <?= $this->headLink() ?>
    <link rel="shortcut icon" href="<?= $this->basePath('favicon.ico') ?>" />
</head>
<body id="body">
<div class="main">
    <div id="header">
        <div class="row">
            <a class="span4" href="/"><img width="235" height="151" src="/img/logo.png" /></a>
            <div class="pull-right">
                <address>
                    «КРАУН ГРУПП» <br>
                    192029, Санкт-Петербург, <br>пр. Обуховской Обороны д.70 корп. 2. <br>
                    (812) 313-19-30 <br />
                    (812) 309-38-13 <br />
                    Пн - Пт с 10:00 до 18:00 (MSK) <br>
                    <a href="mailto:info@crowngroup.ru">info@crowngroup.ru</a>
                </address>
            </div>
        </div>

        <div class="menu-bg">
            <div class="clear">
                <div id="topmenu">
                    <ul class="menu-nav">
                        <li><a href="<?= $this->url('home') ?>">О компании</a></li>
                        <li><a href="<?= $this->url('manufacture') ?>">Производство</a></li>
                        <li><a href="<?= $this->url('production') ?>">Продукция</a></li>
                        <li><a href="<?= $this->url('contacts') ?>">Контакты</a></li>
<!--                        <li><a href="--><?//= $this->url('manage/categories/list') ?><!--">Categories</a></li>-->
<!--                        <li><a href="--><?//= $this->url('manage/products/list') ?><!--">Products</a></li>-->
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div id="wrapper" class="container-fluid">
        <div class="clear row-fluid main">
            <div class="span3">
                <div class="clear">
                    <div class="module-categories">
                        <?=$this->categorieslist(); ?>
                    </div>

                </div>
            </div>
            <div class="span9">

                <?= $this->content ?>

            </div>

        </div>
    </div>

    <div id="footer">
        <div class="space">
            <div class="clear">
                <div class="footerText">
                    <ul class="menu">
                        <li><a href="<?= $this->url('home') ?>">О компании</a></li>
                        <li><a href="<?= $this->url('manufacture') ?>">Производство</a></li>
                        <li><a href="<?= $this->url('production') ?>">Продукция</a></li>
                        <li><a href="<?= $this->url('contacts') ?>">Контакты</a></li>
                    </ul>
                    <div>&copy; 2013 Crowngroup </div>
                    <!--{%FOOTER_LINK} -->
                </div>
            </div>
        </div>
    </div>

</div>

<? $this->headScript()->prependFile($this->basePath('js/jquery-1.9.1.min.js')) ?>
<?= $this->headScript() ?>

</body>
</html>
