<? /* @var $this \Zend\View\Renderer\PhpRenderer */ ?>
<!DOCTYPE html>
<html lang="ru-ru" dir="ltr">
<head>
    <?= $this->headTitle()->setSeparator(' - ') ?>
    <meta charset="UTF-8">
    <meta name="description" content="<?=$this->headTitle()?>">
    <meta http-equiv="Content-Language" content="ru">
    <?= $this->headMeta() ?>

    <? $this->headLink()->prependStylesheet($this->basePath('css/style.css')); ?>
    <?= $this->headLink() ?>
    <link rel="shortcut icon" href="<?= $this->basePath('favicon.ico') ?>" />
</head>
<body id="body">
<div class="main">
    <div id="header" style="text-align: center;">
        <a href="/"><img src="/img/logo.png" style="padding: 15px 0;width: 235px;height:151px;" /></a>
        <div class="menu-bg">
            <div class="clear">
                <div id="topmenu">
                    <ul class="menu-nav">
                        <li class="item53"><a href="/"><span>О компании</span></a></li>
                        <li class="item28"><a href="/dev"><span>Производство</span></a></li>
                        <li class="item29"><a href="/prod"><span>Продукция</span></a></li>
                        <li class="item29"><a href="/contacts"><span>Контакты</span></a></li>
                        <li><a href="<?= $this->url('manage/categories/list') ?>">Categories</a></li>
                        <li><a href="<?= $this->url('manage/products/list') ?>">Products</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div id="wrapper">
        <div class="clear">
            <div id="left">
                <div class="clear">
                    <div class="module-categories">
                        <h3><span>Продукция</span></h3>

                        <div class="boxIndent">
                            <div class="clear">
                                <div id="relative_div" style="position:relative;z-index:0"></div>
                                <ul class="level1">
                                    <li class="level1"><a class="level1" href="/prod/xxx">Костюмные ткани</a></li>
                                    <li class="level1"><a class="level1" href="/prod/xxx">Подкладочные ткани</a></li>
                                    <li class="level1"><a class="level1" href="/prod/xxx">Блузочные и сорочечные ткани</a></li>
                                    <li class="level1"><a class="level1" href="/prod/xxx">Кружево, вышивка на сетке, сетка</a></li>
                                    <li class="level1"><a class="level1" href="/prod/xxx">Флис, полар флис</a></li>
                                    <li class="level1"><a class="level1" href="/prod/xxx">Тканые и печатные этикетки</a></li>
                                    <li class="level1"><a class="level1" href="/prod/xxx">Ленты, шнуры, стропы</a></li>
                                    <li class="level1"><a class="level1" href="/prod/xxx">Пластиковые пломбы и картонные ярлыки</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="container">

                <?= $this->content ?>

            </div>

        </div>
    </div>

    <div id="footer">
        <div class="space">
            <div class="clear">
                <div class="footerText">
                    <ul class="menu">
                        <li class="item53"><a href="/"><span>О компании</span></a></li>
                        <li class="item28"><a href="/dev"><span>Производство</span></a></li>
                        <li class="item29"><a href="/prod"><span>Продукция</span></a></li>
                        <li class="item29"><a href="/contacts"><span>Контакты</span></a></li>
                    </ul>
                    <div>&copy; 2013 Crowngroup </div>
                    <!--{%FOOTER_LINK} -->
                </div>
            </div>
        </div>
    </div>

</div>

<? $this->headScript()->prependFile($this->basePath('js/jquery-1.9.1.min.js')) ?>
<?= $this->headScript() ?>

</body>
</html>
