<? /* @var $this \Zend\View\Renderer\PhpRenderer */ ?>
<!DOCTYPE html>
<html>
<head>
    <?= $this->headTitle('Crown')->setSeparator(' - ') ?>
    <meta charset="UTF-8">
    <?= $this->headMeta() ?>

    <? $this->headLink()->prependStylesheet($this->basePath('css/style.css')); ?>
    <? $this->headLink()->prependStylesheet($this->basePath('css/bootstrap-responsive.min.css')); ?>
    <? $this->headLink()->prependStylesheet($this->basePath('css/bootstrap.min.css')); ?>

    <?= $this->headLink() ?>
    <link rel="shortcut icon" href="<?= $this->basePath('favicon.ico') ?>" />
</head>
<body>

<div id="wrap">
    <div class="container">
        <div class="navbar">
            <div class="navbar-inner">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <i class="icon-cog"></i>
                </a>
                <a class="brand" href="<?= $this->url('home') ?>">
                    Crown Group
                </a>
                <ul class="nav">
                    <li><a href="<?= $this->url('manage/categories/list') ?>">Categories</a></li>
                    <li><a href="<?= $this->url('manage/products/list') ?>">Products</a></li>
                </ul>
            </div>
        </div>
    </div>


    <div class="main">
        <div class="container">

            <? foreach ($this->FlashMessenger()->getErrorMessages() as $message): ?>
                <div class="alert alert-error">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Oh snap!</strong> <?= $message ?>
                </div>
            <? endforeach ?>

            <? foreach ($this->flashMessenger()->getSuccessMessages() as $message): ?>
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Well done!</strong> <?= $message ?>
                </div>
            <? endforeach ?>

            <? foreach ($this->flashMessenger()->getInfoMessages() as $message): ?>
                <div class="alert alert-info">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Heads up!</strong> <?= $message ?>
                </div>
            <? endforeach ?>

            <?= $this->content ?>
        </div>
    </div>

    <div id="push"></div>
</div>

<div id="footer" class="muted">
    <div class="container">
        <p class="credits">
            &copy; 2013 Crown Group.
        </p>
    </div>
</div>

<? $this->headScript()->prependFile($this->basePath('js/jquery-1.9.1.min.js')) ?>

<?= $this->headScript() ?>
</body>
</html>
