<?
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $form \Catalog\Form\CategoryForm
 */
?>

<?=$this->form()->openTag($form->prepare()->setAttribute('class', 'form-horizontal'))?>

    <? foreach ($form as $element): ?>
        <? if ($element instanceof \Zend\Form\Element\Collection): ?>
            <div class="control-group<?= count($element->getMessages()) ? ' error' : '' ?>">
                <label for="<?= $element->getName() ?>" class="control-label"><?=$element->getLabel() ?: ucfirst($element->getName())?></label>

                <div class="controls">

                    <?=$this->formCollection($element->setAttribute('id', $element->getName()))?>
                    <span class="help-inline"><?=$this->formElementErrors($element)?></span>
                </div>
            </div>
        <? else: ?>
            <? /** @var $element \Zend\Form\Element */ ?>
            <div class="control-group<?= count($element->getMessages()) ? ' error' : '' ?>">
                <label for="<?= $element->getName() ?>" class="control-label"><?=$element->getLabel() ?: ucfirst($element->getName())?></label>

                <div class="controls">

                    <?=$this->formElement($element->setAttribute('id', $element->getName()))?>
                    <span class="help-inline"><?=$this->formElementErrors($element)?></span>
                </div>
            </div>
        <? endif; ?>
    <? endforeach; ?>

    <div class="form-actions">
        <input class="btn btn-primary" type="submit" name="submit" value="Create" />
        <a class="btn" href="<?=$this->url('manage/categories/list')?>">Back</a>
    </div>

<?=$this->form()->closeTag($form)?>

<? $this->headLink()->appendStylesheet($this->basePath('css/select2.css')) ?>
<? $this->headScript()->appendFile($this->basePath('js/select2.min.js')) ?>
<? $this->headScript()->appendFile($this->basePath('js/select2_locale_ru.js')) ?>

<? $this->headScript()->captureStart() ?>
//<script type="text/javascript">
    (function() {
        $('#categories').select2({width: 220});
    })();
//</script>
<? $this->headScript()->captureEnd() ?>
