<?
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $products \Catalog\Entity\Product[]
 */
?>

<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered table-advance table-hover" id="products">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Categories</th>
                <th class="span3">Actions</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="4">
                    <a class="btn btn-primary" href="<?=$this->url('manage/products/create')?>">
                        <i class="icon-plus-sign icon-white"></i>
                        Add Product
                    </a>
                </td>
            </tr>
            </tfoot>
            <tbody>
            <? foreach($products as $product): ?>
                <tr>
                    <td><?=$product->getId()?></td>
                    <td><?=$product->getName()?></td>
                    <td><?=implode(', ', $product->getCategories()->toArray())?></td>
                    <td>
                        <a class="btn" href="<?=$this->url('manage/products/update', array('id' => $product->getId()))?>">
                            <i class="icon-edit"></i>
                            Edit
                        </a>
                        <a onclick="return confirm('Really?')" class="btn btn-danger" href="<?=$this->url('manage/products/delete', array('id' => $product->getId()))?>">
                            <i class="icon-minus-sign icon-white"></i>
                            Delete
                        </a>
                    </td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div>
</div>


<?// $this->headLink()->appendStylesheet($this->basePath('assets/data-tables/DT_bootstrap.css')) ?>
<?// $this->headScript()->appendFile($this->basePath('assets/data-tables/jquery.dataTables.js')) ?>
<?// $this->headScript()->appendFile($this->basePath('assets/data-tables/DT_bootstrap.js')) ?>
<?// $this->headScript()->appendFile($this->basePath('js/jquery/data-tables/datatables.js')) ?>
<!---->
<?// $this->headScript()->captureStart() ?>
<!--//<script type="text/javascript">-->
<!--    (function() {-->
<!--        $('#users').dataTable();-->
<!--    })();-->
<!--    //</script>-->
<?// $this->headScript()->captureEnd() ?>
