<?
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $products \Catalog\Entity\Product[]
 * @var $category \Catalog\Entity\Category
 */
?>
<div class="well">
<?=$this->navigation()->breadcrumbs($this->categorieslist()->getContainer()) ?>
</div>
<div class="grid grid-triple">
    <? foreach ($products as $product): ?>
        <div class="cell">
            <div class="product">
                <a href="<?=$this->url('products/list-by-category/view', ['slug' => $category->getSlug(), 'name' => $product->getName()])?>">
                    <? if ($product->getImages()->count()): ?>
                        <img class="preview-small" src="<?=$this->url('products/get-image', ['id' => $product->getImages()->first()->getId()])?>" alt="<?=$product->getName()?>" />
                    <? endif; ?>
                </a>
                <p class="name">
                    <a href="<?=$this->url('products/list-by-category/view', ['slug' => $category->getSlug(), 'name' => $product->getName()])?>">
                        <?=$product->getName()?>
                    </a>
                </p>
            </div>
        </div>
    <? endforeach; ?>
</div>