<div class="module-specials">
    <h3><span><a href="<?= $this->url('warehouse') ?>">Ткани на складе</a></span></h3>

    <div class="grid grid-double boxIndent">
        <div class="cell">
            <div class="product">
                <a target="_blank" href="<?=$this->basePath('resources/lining.pdf')?>">
                    <img class="preview-small" src="<?=$this->basePath('img/lining.jpg')?>" alt="Подкладка" />
                    <p>Подкладка</p>
                </a>
            </div>
        </div>

        <div class="cell">
            <div class="product">
                <a target="_blank" href="<?=$this->basePath('resources/fleece.pdf')?>">
                    <img class="preview-small" src="<?=$this->basePath('img/1.jpg')?>" alt="Флис" />
                    <p>Флис</p>
                </a>
            </div>
        </div>
    </div>
</div>